#!/usr/bin/env bash
# Profile authoring helpers: derive a clean name, recognise a clonable URL, and
# render a profile file from the DETECT_* globals (see lib/detect.sh). Kept in a
# sourceable lib (not inline in `fwf`) so the functional test suite can exercise
# them directly. 3.2-clean.

# Derive a clean profile/worktree name from a git URL or path.
derive_name() { # $1 = url|path
  local b="$1"
  b="${b%/}"; b="${b%.git}"; b="$(basename "$b")"
  printf '%s' "$b" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9-' '-' | sed -E 's/-+/-/g; s/^-|-$//g'
}

# True if $1 looks like a remote we should clone.
is_url() { # $1
  case "$1" in *://*|git@*|*.git) return 0;; *) return 1;; esac
}

# Render a profile file. Fail-closed: an unknown gate becomes a command that
# ERRORS, so QA never silently merges everything on a repo we couldn't detect.
fwf_write_profile() { # $1=out $2=name $3=repo $4=wt_base $5=default_branch
  local out="$1" name="$2" repo="$3" wt_base="$4" defbr="$5"
  local gate="$DETECT_GATE" build="$DETECT_BUILD" e2e="$DETECT_E2E" dev="$DETECT_DEV" e2e_setup=""
  [ -n "$gate" ]  || gate='echo "fwf: set GATE_CMD in this profile (no test command detected)" >&2; false'
  [ -n "$build" ] || build='true'
  [ -n "$e2e" ]   || e2e='true'   # no e2e suite -> conductor promotes staging->integration unguarded
  case "$e2e" in *playwright*) e2e_setup="${e2e% *} install";; esac  # browsers must be installed first

  cat > "$out" <<EOF
#!/usr/bin/env bash
# shellcheck disable=SC2034  # profile vars are consumed by lib.sh and the engine scripts
# fun-with-friends profile: $name   (generated by 'fwf init')
# Detected ecosystem: $DETECT_KIND.
# Everything here is overridable by the matching FWF_* env var. Edit any command
# below to taste, then run: fwf --profile $name up

FWF_REPO="\${FWF_REPO:-$repo}"                 # the application repo (source of truth)
WT_PREFIX="\${FWF_WT_PREFIX:-$name}"           # worktrees: \${WT_PREFIX}-impl1, -qa1, ...
WT_BASE="\${FWF_WT_BASE:-$wt_base}"            # worktrees live here (kept out of \$HOME)

STAGING_BRANCH="\${FWF_STAGING_BRANCH:-staging}"             # impl PRs target this; QA fast-gates + merges here
INTEGRATION_BRANCH="\${FWF_INTEGRATION_BRANCH:-integration}" # conductor e2e-promotes here (your release source)
DEFAULT_BRANCH="\${FWF_DEFAULT_BRANCH:-$defbr}"              # released by you; the swarm never touches it

# Commands run inside a worktree ---------------------------------------------
GATE_CMD='$gate'
BUILD_CMD='$build'
E2E_CMD='$e2e'
E2E_SETUP_CMD='$e2e_setup'   # one-time e2e dep install in the conductor tree (empty = none)

# Live-dev hint shown to implementers (use __DATA__ for a per-tree data dir).
DEV_UI_HINT='$dev'

# This repo has no isolated per-worktree dev data; the no-op defaults in
# config.sh apply. If it does, override data_dir()/seed_data() here.
EOF
}
